script_template: "custom-inno-setup-script.iss"
app_id: ProjectOcean.Launcher
publisher_name: Project Ocean
publisher_url: https://github.com/AkoDevelopment
display_name: Project Ocean
install_dir_name: Project Ocean
create_desktop_icon: true
locales:
  - en